In [1]:
import numpy as np

In [2]:
my_list = [10,20,30],[40,50,60],[70,80,90]
matrix = np.array(my_list)
matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
a = np.arange(6) 
a

array([0, 1, 2, 3, 4, 5])

In [38]:
b = np.arange(9).reshape(3, 3)
b


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
b = [0,1,3],[0,1,4],[5,4,6]
n = np.array(b)
n

array([[0, 1, 3],
       [0, 1, 4],
       [5, 4, 6]])

In [42]:
sum = n+b
sum

array([[ 0,  2,  6],
       [ 0,  2,  8],
       [10,  8, 12]])

In [34]:
d = np.arange(32).reshape(2, 4, 4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [26]:
c.dtype

dtype('int64')

In [27]:
c.data

In [30]:
c.ndim

3

In [49]:
f =np.hsplit(a, 3)
f

[array([0, 1]), array([2, 3]), array([4, 5])]

In [50]:
a

array([0, 1, 2, 3, 4, 5])